### ISSUE TITLE
As a Price Checker I can search parts and services from local sellers 

### ISSUE THREAD

**Issue by Asemota33** [COMP231W21-G5/Mechanic-Checker#1]
- [x]  #12 Creating a database table for the products and sellers 
- [x]  #13 Creating a database for storing product images into s3 bucket 
- [x]  #14 Create GUI for search bar and homepage
- [x]  #15 Code functionality for filtering based on search query keyword(s)  
- [x]  #16 Research about implementation of google geolocation and code functionality 
- [x]  #17 Implement testing scripts to satisfy the acceptance criteria
