### ISSUE TITLE
Implement Searching functionality using eBay API

### ISSUE THREAD

**Issue by Asemota33** [COMP231W21-G5/Mechanic-Checker#117]
- [x] #118 Documentation for searching using eBay API
- [x] #119 Add API Keys to Database for Big Box retailers and create function to get it
- [x] #120 Parse and convert JSON response from eBay API
- [x] #121 Create Big Box retailer Seller Record in Database for storing logo images
