### ISSUE TITLE
As a price checker I would like to view the results of vehicle parts and services that matches a search 

### ISSUE THREAD

**Issue by Asemota33** [COMP231W21-G5/Mechanic-Checker#2]
- [x]  #18 Create Gui for showing results 
- [x]  #19 Display products based on response 
- [x]  #20 Filter returned products based on filter options  
- [x] #21 Implement testing scripts to satisfy the acceptance criteria
