### ISSUE TITLE
Research eBay API to get a better understanding and familiarize ourselves with it. 

### ISSUE THREAD

**Issue by Asemota33** [COMP231W21-G5/Mechanic-Checker#3]
- [x] #22 Experiment with request and responses with API  
- [x] #25 Investigate API with NodeJS application 
- [x] #26 Figure out how to test API 
- [x] #27 Figure out how to deploy API 
- [x] #112 Figure our how to filter json responses from eBay API
