### ISSUE TITLE
Research Alibaba API to get a better understanding and familiarize ourselves with it. 

### ISSUE THREAD

**Issue by Asemota33** [COMP231W21-G5/Mechanic-Checker#4]
- [x] #28 Experiment with request and responses with API  
- [x] #32 Figure out how to test API 
- [x] #33 Figure out how to deploy API 
- [x] #37 Investigate API with NodeJS application
- [x] #113 Figure out how to filter json responses from Alibaba API
