### ISSUE TITLE
Research Amazon API to get a better understanding and familiarize ourselves with it. 

### ISSUE THREAD

**Issue by Asemota33** [COMP231W21-G5/Mechanic-Checker#5]
- [x] #34 Experiment with request and responses with API  
- [x] #31 Investigate API with NodeJS application 
- [x] #38 Figure out how to test API 
- [x] #39 Figure out how to deploy API 
- [x] Figure our how to filter json responses from Amazon API
