### ISSUE TITLE
As a price checker I would like to view the details of my selected part or service 

### ISSUE THREAD

**Issue by Asemota33** [COMP231W21-G5/Mechanic-Checker#7]
- [x] #44 Develop GUI for viewing details of selected part or service (Seperate Screen)
- [x] #45 Develop code for controller to transfer data of selected product to view details page  
- [x] #46 Documentation for viewing details of selected product in seller inventory
