### ISSUE TITLE
As a seller I would like to sign up for an account to promote my parts and services 

### ISSUE THREAD

**Issue by Asemota33** [COMP231W21-G5/Mechanic-Checker#8]
- [x] #47 Create GUI for sign up
- [x] #48 Develop code for sending verification email after seller signs up (using sendgrid ) 
- [x] #49 Develop code for sending reset email after seller goes through reset password process (using sendgrid ) 
- [ ] #50 Documentation for signing up as a seller to the mechanic checker app
- [x] #51 Create GUI for Sign In Page
- [ ] #52 Authenticate Seller Log in. 
- [x] #53 Create GUI for Seller Log In landing page
- [x] #54 Develop code to add seller logo to s3 bucket, and check for errors  
- [x] #122 Develop code to search through list of products
